apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
    environment: production
    tier: frontend
  annotations:
    description: "This pod runs the frontend application for production."
    owner: "team-frontend"
spec:
  containers:
  - name: myapp-container
    image: nginx:latest
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
    environment: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80