apiVersion: v1
kind: Pod
metadata:
  name: security-context
spec:
  containers:
    - name: security-context
      image: nginx
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 1000
        capabilities: # Capabilities are only supported at the container level, not the pod level.
          add:
            - NET_ADMIN
            - NET_RAW
          drop:
            - ALL