apiVersion: v1
kind: Pod
metadata:
  name: taint-toleration-example
spec:
  containers:
    - name: example-container
      image: nginx
  tolerations: # Kubectl taint nodes node1 app=blue:NoSchedule
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"